default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: dmitro24
  pool: 25

development:
  <<: *default
  database: work
  pool: 25

test:
  <<: *default
  database: work_test

production:
  <<: *default
  database: work_production
  username: clouduser
  password: MacBook1992
  pool: 25
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
  secret_key_base: